# Generated by Django 2.0.13 on 2019-04-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190403_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='loan_status',
            field=models.CharField(choices=[('m', 'Maintenance'), ('o', 'On Loan'), ('a', 'Available')], default='a', max_length=1),
            preserve_default=False,
        ),
    ]
