# Generated by Django 2.0.13 on 2019-04-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('product', '0004_product_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='return_note',
            field=models.TextField(blank=True, help_text='Where you left the demo and any notes on condition', null=True),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='returned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse'),
        ),
    ]
