# Generated by Django 2.0.13 on 2019-04-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190403_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='returned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse'),
        ),
    ]
