# Generated by Django 2.0.13 on 2019-04-04 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190404_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='returned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse'),
        ),
    ]
