# Generated by Django 2.0.13 on 2019-04-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190404_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='human_readable_name',
            field=models.CharField(default='place holder', max_length=255),
            preserve_default=False,
        ),
    ]
