# Generated by Django 2.0.13 on 2019-04-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_current_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='rental_start',
        ),
    ]
