# Generated by Django 2.0.13 on 2019-04-18 19:58

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190416_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=product.models.manufacturer_directory),
        ),
    ]
