# Generated by Django 2.0.13 on 2019-05-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20190503_1130'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manufacturer',
            table='manufacturer_manufacturer',
        ),
    ]
