# Generated by Django 2.0.13 on 2019-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_delete_old_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='return_note',
            field=models.TextField(blank=True, default='none', help_text='Where you left the demo and any notes on condition'),
            preserve_default=False,
        ),
    ]
