# Generated by Django 2.0.13 on 2019-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_move_manufacturer_and_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(default='none'),
            preserve_default=False,
        ),
    ]
