# Generated by Django 2.0.13 on 2019-05-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0002_manufacturer_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='website',
        ),
    ]
